[package]
name = "hopter"
version = "0.1.8"
edition = "2021"
crate-type = ["staticlib"]

[features]
default = ["unwind"]
unwind = ["dep:gimli", "dep:fallible-iterator"]

[dependencies]
static_assertions = "1.1"
heapless = "0.8"
spin = "0.9"
int-enum = "1.1"
cortex-m-semihosting = "0.5"
concat-idents = "1.0"
crc32fast = { version = "1.4.2", default-features = false }


[dependencies.hopter_proc_macro]
git = "https://github.com/ZhiyaoMa98/hopter-procedural-macro.git"
tag = "v0.1.3"

[dependencies.hopter_conf_params]
git = "https://github.com/ZhiyaoMa98/hopter-conf-params.git"
tag = "v0.1.2"

[dependencies.cortex-m]
version = "0.7"
features = ["inline-asm"]

[dependencies.owning_ref]
git = "https://github.com/theseus-os/owning-ref-rs.git"

[dependencies.crossbeam]
version = "0.8"
default-features = false

[dependencies.gimli]
version = "0.29"
default-features = false
features = ["read"]
optional = true

[dependencies.fallible-iterator]
version = "0.3"
default-features = false
optional = true

[dependencies.intrusive-collections]
version = "0.9"
features = ["nightly"]

[dev-dependencies]
nb = "1.1"

[dev-dependencies.stm32f4xx-hal]
git = "https://github.com/ZhiyaoMa98/stm32f4xx-hal.git"
branch = "dependency"
default-features = false
features = ["stm32f405"]

[[example]]
name = "test-sync-mailbox-notify_by_task"
path = "examples/tests/sync/mailbox/notify_by_task.rs"

[[example]]
name = "test-sync-mailbox-notify_in_advance"
path = "examples/tests/sync/mailbox/notify_in_advance.rs"

[[example]]
name = "test-sync-mailbox-task_timeout"
path = "examples/tests/sync/mailbox/task_timeout.rs"

[[example]]
name = "test-sync-mailbox-task_not_timeout"
path = "examples/tests/sync/mailbox/task_not_timeout.rs"

[[example]]
name = "test-sync-mailbox-notify_in_advance_after_timeout"
path = "examples/tests/sync/mailbox/notify_in_advance_after_timeout.rs"

[profile.release]
lto = "off"
