//! This module contains code to support intrusive link lists of task objects.
//! Task objects are type erased to be [`Arc<dyn TaskTrait>`](TaskTrait).
//!
//! The implementation of [`TaskFatLink`] to support `dyn` objects in an
//! intrusive linked list is inspired by Conrad Ludgate.
//! Original discussion: https://github.com/Amanieu/intrusive-rs/issues/91

use super::TaskTrait;
use alloc::sync::Arc;
use core::{mem::offset_of, ptr::NonNull};
use intrusive_collections::{
    linked_list::{AtomicLinkOps, LinkedListOps},
    Adapter, DefaultLinkOps, DefaultPointerOps, LinkOps, LinkedList, LinkedListAtomicLink,
};

/// A link type used to chain task structs to form an intrusive linked list.
/// The link is fat because it stores additional information to allow the
/// intrusive link list to hold elements of type [`dyn TaskTrait`](TaskTrait).
pub(crate) struct TaskFatLink {
    /// The actual link chaining task structs.
    thin_link: LinkedListAtomicLink,
    /// An associated function for each concrete type implementing [`TaskTrait`],
    /// which is used to derive a pointer to the container task object from a
    /// given pointer to the link field.
    ///
    /// Below shows the layout of a task struct, as well as the argument and
    /// the return value of the associated function.
    ///
    /// ```plain
    ///    address low
    /// +--------------+ <- return value: *const dyn pointer to container task
    /// | other fields |                  struct object
    /// +--------------+ <- argument: pointer to link field
    /// |   fat link   |
    /// +--------------+
    /// | other fields |
    /// +--------------+
    ///   address high
    /// ```
    fat_link_to_container: unsafe fn(link: NonNull<TaskFatLink>) -> *const dyn TaskTrait,
}

impl TaskFatLink {
    /// Create a fat link for a concrete task type.
    pub(super) const fn new<T>() -> Self
    where
        T: FatLinked,
    {
        TaskFatLink {
            thin_link: LinkedListAtomicLink::new(),
            // The function is created for each concrete task type.
            fat_link_to_container: T::fat_link_to_container,
        }
    }
}

/// Given a pointer to this fat link, return a pointer to its thin link
/// field.
fn fat_link_ptr_to_thin(ptr: NonNull<TaskFatLink>) -> NonNull<LinkedListAtomicLink> {
    let offset = offset_of!(TaskFatLink, thin_link);

    // Safety: The offset is generated by the compiler so it must be correct.
    // The returned pointer is valid as long as the input argument is valid.
    unsafe { NonNull::new_unchecked(ptr.as_ptr().byte_add(offset).cast()) }
}

/// Given a pointer to a thin link within a fat link, return the pointer to
/// the fat link containing it.
///
/// Safety:
/// - The given thin link must be inside a fat link.
unsafe fn thin_link_ptr_to_fat(link: NonNull<LinkedListAtomicLink>) -> NonNull<TaskFatLink> {
    let offset = offset_of!(TaskFatLink, thin_link);

    // Safety: The offset is generated by the compiler so it must be correct.
    // The returned pointer is valid as long as the input argument is valid.
    unsafe { NonNull::new_unchecked(link.as_ptr().byte_sub(offset).cast()) }
}

/// A concrete task type should implement this trait so that the object
/// instance can be placed in an instrusive linked list containing type of
/// [`dyn TaskTrait`](TaskTrait).
///
/// Safety:
/// - The type implementing this trait must contain a field of type
///   [`TaskFatLink`].
/// - The type implementing this trait must also implement the
///   [`TaskTrait`] trait.
pub(crate) unsafe trait FatLinked {
    /// Given a pointer to an object that implements [`FatLinked`], return a
    /// pointer that points to the fat link field.
    ///
    /// Safety:
    /// - `self` must point to a valid object that implements [`FatLinked`].
    unsafe fn container_to_fat_link(self: *const Self) -> NonNull<TaskFatLink>;
    /// Given a pointer to a fat link field inside an object that implements
    /// [`FatLinked`], return a pointer that points to the object, and the
    /// returned pointer has type [`*const dyn TaskTrait`](TaskTrait).
    ///
    /// The function is constrained by `Self: Sized` so it does not apply to
    /// trait object, i.e. making it explicitly non-dispatchable.
    /// https://doc.rust-lang.org/reference/items/traits.html#object-safety
    unsafe fn fat_link_to_container(ptr: NonNull<TaskFatLink>) -> *const dyn TaskTrait
    where
        Self: Sized;
}

/// The link operations to manipulate the link to form a linked list. The link
/// operations are designed to be a struct to allow stateful operations, but in
/// our case the operations are simple and stateless. So this is a zero-sized
/// struct and only the methods are meaningful.
pub(crate) struct FatLinkOps {
    /// The default statelss operations provided by the intrusive collections
    /// library.
    ops: AtomicLinkOps,
}

impl FatLinkOps {
    const fn new() -> Self {
        FatLinkOps {
            ops: <LinkedListAtomicLink as DefaultLinkOps>::NEW,
        }
    }
}

// The acquire and release link operation on the fat link simply just manipulate
// the underlying thin link field.
unsafe impl LinkOps for FatLinkOps {
    type LinkPtr = NonNull<TaskFatLink>;

    unsafe fn acquire_link(&mut self, ptr: Self::LinkPtr) -> bool {
        self.ops.acquire_link(fat_link_ptr_to_thin(ptr))
    }

    unsafe fn release_link(&mut self, ptr: Self::LinkPtr) {
        self.ops.release_link(fat_link_ptr_to_thin(ptr))
    }
}

// The operations to form a linked list similarly act on the thin link field
// within the fat link.
unsafe impl LinkedListOps for FatLinkOps {
    unsafe fn next(&self, ptr: Self::LinkPtr) -> Option<Self::LinkPtr> {
        self.ops
            .next(fat_link_ptr_to_thin(ptr))
            .map(|ptr| thin_link_ptr_to_fat(ptr))
    }

    unsafe fn prev(&self, ptr: Self::LinkPtr) -> Option<Self::LinkPtr> {
        self.ops
            .prev(fat_link_ptr_to_thin(ptr))
            .map(|ptr| thin_link_ptr_to_fat(ptr))
    }

    unsafe fn set_next(&mut self, ptr: Self::LinkPtr, next: Option<Self::LinkPtr>) {
        self.ops
            .set_next(fat_link_ptr_to_thin(ptr), next.map(fat_link_ptr_to_thin))
    }

    unsafe fn set_prev(&mut self, ptr: Self::LinkPtr, prev: Option<Self::LinkPtr>) {
        self.ops
            .set_prev(fat_link_ptr_to_thin(ptr), prev.map(fat_link_ptr_to_thin))
    }
}

/// The adapter type defining operations to allow instances of a type to be
/// managed as an intrusive linked list. The operations are designed to be a
/// struct to allow stateful operations, but in our case the operations are
/// simple and stateless. So this is a zero-sized struct and only the methods
/// are meaningful.
pub(crate) struct TaskListAdapter {
    /// Operations for manilupating the links.
    link_ops: FatLinkOps,
    /// Operations for casting between raw pointers and `Arc<dyn TaskTrait>`.
    pointer_ops: DefaultPointerOps<Arc<dyn TaskTrait>>,
}

impl TaskListAdapter {
    pub const fn new() -> Self {
        TaskListAdapter {
            link_ops: FatLinkOps::new(),
            pointer_ops: DefaultPointerOps::<Arc<dyn TaskTrait>>::new(),
        }
    }
}

// Implement the required interfaces to allow `Arc<dyn TaskTrait>` to be
// inserted into an intrusive linked list.
unsafe impl Adapter for TaskListAdapter {
    type LinkOps = FatLinkOps;
    type PointerOps = DefaultPointerOps<Arc<dyn TaskTrait>>;

    /// Get a pointer to an object from a pointer to a link in that object.
    unsafe fn get_value(&self, fat_link: NonNull<TaskFatLink>) -> *const dyn TaskTrait {
        let fat_link_to_container = (*fat_link.as_ptr()).fat_link_to_container;
        fat_link_to_container(fat_link)
    }

    /// Get a pointer to the link inside the given object (the container).
    unsafe fn get_link(&self, container: *const dyn TaskTrait) -> NonNull<TaskFatLink> {
        container.get_link()
    }

    /// Return a reference to the link operations.
    fn link_ops(&self) -> &Self::LinkOps {
        &self.link_ops
    }

    /// Return a mutable reference to the link operations.
    fn link_ops_mut(&mut self) -> &mut Self::LinkOps {
        &mut self.link_ops
    }

    /// Return a reference to the pointer converter.
    fn pointer_ops(&self) -> &Self::PointerOps {
        &self.pointer_ops
    }
}

/// Additional interfaces for task lists.
pub(crate) trait TaskListInterfaceExt {
    fn push_back_tick_sorted(&mut self, new_task: Arc<dyn TaskTrait>);
    fn pop_highest_priority(&mut self) -> Option<Arc<dyn TaskTrait>>;
}

impl TaskListInterfaceExt for LinkedList<TaskListAdapter> {
    /// Push a new task into the linked list. Maintain ascending order w.r.t.
    /// the tick number to wake up.
    fn push_back_tick_sorted(&mut self, new_task: Arc<dyn TaskTrait>) {
        let mut cursor_mut = self.front_mut();

        // Move the cursor until we encounter a task with a higher wake up tick
        // number or we are at the end of the list.
        while let Some(task) = cursor_mut.get() {
            if new_task.get_wake_tick() < task.get_wake_tick() {
                break;
            }
            cursor_mut.move_next();
        }

        // Panics if the task is already in a list, i.e., the linked field in
        // the task struct is already in use.
        cursor_mut.insert_before(new_task);
    }

    /// Pop out the task with the highest priority in the linked list. If
    /// there are multiple tasks having the highest priority, the one in the
    /// front will be popped out. Return `None` if the list is empty.
    fn pop_highest_priority(&mut self) -> Option<Arc<dyn TaskTrait>> {
        let mut cursor = self.front();

        // Get the priority of the first task in the list.
        let mut max_prio = match cursor.get() {
            Some(task) => task.get_priority(),
            None => return None,
        };
        let mut max_pos = 0usize;

        // Move the cursor to the next element.
        cursor.move_next();

        // Record the position of the cursor.
        let mut cur_pos = 1usize;

        // Scan through the linked list. Whenever we see a task with higher
        // priority than all scanned tasks, update the position.
        while let Some(task) = cursor.get() {
            let cur_prio = task.get_priority();

            // Update the position if we see higher priority.
            // Smaller numerical value represents higher priority.
            if cur_prio < max_prio {
                max_pos = cur_pos;
                max_prio = cur_prio;
            }

            cursor.move_next();
            cur_pos += 1;
        }

        // Move the cursor to the task with the highest priority.
        let mut cursor = self.front_mut();
        for _ in 0..max_pos {
            cursor.move_next();
        }

        // Pop out the chosen task.
        cursor.remove()
    }
}
