name: Run ELF Image for Testing
description: "Run the given ELF image with QEMU and compare the output with ground truth."

inputs:
  cookie:
    description: "Cookie for download authorization."
    required: true
  category:
    description: "The name of the test category."
    required: true
  sub-category:
    description: "The name of the test sub-category."
    required: true
  test-name:
    description: "Name of the test to be run."
    required: true
  timeout:
    description: "Timeout to prevent unresponsive QEMU."
    required: false
    default: 5s

runs:
  using: "composite"
  steps:
    - name: Prepare QEMU
      uses: ./.github/workflows/actions/prepare-qemu
      with:
        cookie: ${{ inputs.cookie }}

    - name: Download ELF image test-${{ inputs.category }}-${{ inputs.sub-category }}-${{ inputs.test-name }}
      uses: actions/download-artifact@v4
      with:
        name: test-${{ inputs.category }}-${{ inputs.sub-category }}-${{ inputs.test-name }}
        path: ./artifacts

    - name: Run test ${{ inputs.test-name }}
      run: |
        timeout ${{ inputs.timeout }} \
          qemu-system-arm -machine netduinoplus2 -nographic \
          -semihosting-config enable=on,target=native \
          -kernel "./artifacts/test-${{ inputs.category }}-${{ inputs.sub-category }}-${{ inputs.test-name }}" \
          > output.txt
      shell: bash

    - name: Print output
      run: cat output.txt
      shell: bash

    - name: Check test output
      run: |
        diff output.txt \
          "examples/tests/${{ inputs.category }}/${{ inputs.sub-category }}/${{ inputs.test-name }}.txt"
      shell: bash
