name: All Test Cases

on:
  workflow_call:
    secrets:
      cookie:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  sync:
    uses: ./.github/workflows/sync.yaml
    secrets:
      cookie: ${{ secrets.cookie }}
